### ISSUE TITLE
Is the dataset available?

### ISSUE THREAD

**Issue by sagnik** [schlevik/dataset-analysis#1]
Hi, is the dataset available?

**Comment by schlevik** [comment]
Hi, thanks for your interest!

Good question actually. I thought you could find it under the appropriate entry here:

https://lrec2020.lrec-conf.org/en/shared-lrs/

however, it seems as if they have some sort of database mishap, because the resource is labelled wrongly.

Anyhow, this is the direct link:

http://lrec2020.lrec-conf.org/sharedlrs2020/16_res_1.tgz

It's in [brat](https://brat.nlplab.org/) format, but you can convert it in json/csv as you wish.

Hope that helps!

**Comment by sagnik** [comment]
Thank you, that does help!
